# site settings
title: Insta-goal
subtitle: subtitle in progress
email: angelina.abitino@colorado.edu
description: A project for CSCI 5839
baseurl: "/forty-jekyll-theme" # the subpath of your site, e.g. /blog
url: # the base hostname & protocol for your site
author: This is the author
street_address: Idea Forge 
                2445 Kittredge Loop Dr 
city: Boulder
state: CO
zip_code: 80309
country: USA
phone: (321) 271-0596

# homepage tiles
tiles-source: posts # accepts "posts" or "pages"
tiles-count: 4

# social settings (key must match name of font awesome icon)
# see https://fontawesome.com/icons?d=gallery&p=2&s=brands
# Icons are not shown if value is empty
# You need to restart jekyll for changes to have an effect
socials:
  GitHub: https://github.com/angelina-abitino
  LinkedIn: https://www.linkedin.com/in/angelinaabitino

# build settings
markdown: kramdown

sass:
  style: compressed

exclude:
- "*.gemspec"
- LICENSE.md
- CONTRIBUTING.md
- README.md 
